# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pos-web-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://poswebacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_97fd1d441a5347378c615c2beb206012 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9356ccbf042242d8ab3153e4086f4d7a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: poswebacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_97fd1d441a5347378c615c2beb206012 }}/pos.app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pos-web-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c2a4d7e14b094cdfab94b74819da5541 }}
        images: 'poswebacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_97fd1d441a5347378c615c2beb206012 }}/pos.app:${{ github.sha }}'
